version: 2

references:
  container_config: &container_config
    docker:
      - image: circleci/node:10.13.0
    working_directory: ~/portfolio

jobs:
  build:
    <<: *container_config
    steps:
      - checkout
      - run:
          name: System information
          command: |
            echo "Node $(node -v)"
            echo "Yarn v$(yarn --version)"
      - restore_cache:
          name: Restore Yarn Package Cache
          key: dependency-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: yarn --ignore-engines
      - save_cache:
          name: Save Yarn Package Cache
          key: dependency-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run:
          name: Build
          command: yarn run build
      - run:
          name: Test
          command: yarn test
